"use client";

import { use, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

// R48_NO_INVITE_UI_01, redemption half.
//
// This route is NOT in middleware.ts's PROTECTED_PREFIXES, deliberately: an
// invited person is by definition not a member of anything yet, and often not
// signed in at all. Bouncing them to /login without ever showing what they
// were invited to is how invite flows lose people.
//
// The link is generated by PROJEXA itself (see api/org/invites/route.ts), so
// nothing here depends on Supabase's {{ .SiteURL }} email template or on the
// redirect allowlist.

type Preview = {
  organization_name: string;
  role: string;
  expires_at: string;
  is_open: boolean;
};

const ROLE_LABEL: Record<string, string> = {
  owner: "Owner",
  admin: "Administrator",
  pm: "Project Manager",
  site_engineer: "Site Engineer",
  member: "Member",
  client_viewer: "Client (read-only)",
};

export default function InvitePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params);
  const router = useRouter();

  const [preview, setPreview] = useState<Preview | null>(null);
  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [accepting, setAccepting] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const supabase = createClient();
      const { data: session } = await supabase.auth.getSession();
      if (!cancelled) setSignedIn(!!session.session);

      const res = await fetch(`/api/org/invites/preview?token=${encodeURIComponent(token)}`);
      const body = await res.json().catch(() => ({}));
      if (cancelled) return;
      if (!res.ok) {
        setError((body as { error?: string }).error ?? "This invitation link is not valid.");
        return;
      }
      setPreview((body as { invite: Preview }).invite);
    })();
    return () => {
      cancelled = true;
    };
  }, [token]);

  const accept = useCallback(async () => {
    setAccepting(true);
    setError(null);
    const res = await fetch("/api/org/invites/accept", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ token }),
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) {
      setError((body as { error?: string }).error ?? "Could not accept this invitation.");
      setAccepting(false);
      return;
    }
    router.replace("/dashboard");
    router.refresh();
  }, [token, router]);

  return (
    <main className="flex min-h-screen items-center justify-center bg-px-concrete p-6">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="font-heading text-xl">
            {preview ? `Join ${preview.organization_name}` : "Invitation"}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {error && (
            <p role="alert" className="text-sm text-px-error">
              {error}
            </p>
          )}

          {!error && !preview && <p className="text-sm text-px-muted">Checking this invitation…</p>}

          {preview && !preview.is_open && !error && (
            <p role="alert" className="text-sm text-px-error">
              This invitation is no longer open. It has been used, revoked, or has expired. Ask an
              administrator for a new one.
            </p>
          )}

          {preview && preview.is_open && (
            <>
              <p className="text-sm text-px-muted">
                You have been invited to join <strong className="text-px-ink">{preview.organization_name}</strong> as{" "}
                <strong className="text-px-ink">{ROLE_LABEL[preview.role] ?? preview.role}</strong>.
              </p>

              {signedIn === false && (
                <>
                  <p className="text-sm text-px-muted">
                    Sign in with the email address this invitation was sent to, and you will come straight back
                    here.
                  </p>
                  <Button
                    className="w-full"
                    onClick={() => router.push(`/login?redirectTo=${encodeURIComponent(`/invite/${token}`)}`)}
                  >
                    Sign in to accept
                  </Button>
                </>
              )}

              {signedIn === true && (
                <Button className="w-full" onClick={accept} disabled={accepting}>
                  {accepting ? "Joining…" : `Join ${preview.organization_name}`}
                </Button>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </main>
  );
}
