// Generates the Apps Script source an org admin pastes once into
// Extensions -> Apps Script on the org's spreadsheet (see the "Why an Apps
// Script paste step, not full auto-deployment" note in the feature plan).
// The token/org id/base URL are baked directly into the generated text, so
// there is no manual configuration step beyond paste + save + reload --
// clicking the menu item is the entire admin-facing setup.

export function buildAppsScriptSource(options: { webhookToken: string; organizationId: string; baseUrl: string }): string {
  const { webhookToken, organizationId, baseUrl } = options;
  return `// Generated by PROJEXA for organization ${organizationId}.
// Do not share this file -- WEBHOOK_TOKEN authenticates every sync request
// as this organization. Regenerate it from PROJEXA's Settings page (Google
// Sheets card -> Disconnect, then Connect again) if it is ever exposed.
const WEBHOOK_TOKEN = ${JSON.stringify(webhookToken)};
const ORGANIZATION_ID = ${JSON.stringify(organizationId)};
const BASE_URL = ${JSON.stringify(baseUrl)};

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('PROJEXA')
    .addItem('Refresh Data from PROJEXA', 'refreshFromProjexa')
    .addItem('Submit My Changes', 'submitToProjexa')
    .addToUi();
}

function refreshFromProjexa() {
  callWebhook_('refresh');
}

function submitToProjexa() {
  callWebhook_('submit');
}

function callWebhook_(action) {
  const ui = SpreadsheetApp.getUi();
  try {
    const response = UrlFetchApp.fetch(BASE_URL + '/api/integrations/google-sheets/webhook', {
      method: 'post',
      contentType: 'application/json',
      headers: { Authorization: 'Bearer ' + WEBHOOK_TOKEN },
      payload: JSON.stringify({ action: action, organizationId: ORGANIZATION_ID }),
      muteHttpExceptions: true,
    });
    const status = response.getResponseCode();
    const body = JSON.parse(response.getContentText() || '{}');
    if (status >= 200 && status < 300) {
      if (action === 'submit') {
        ui.alert('PROJEXA sync complete', (body.succeeded || 0) + ' row(s) succeeded, ' + (body.failed || 0) + ' failed. Check the Result column on each tab for details.', ui.ButtonSet.OK);
      } else {
        ui.alert('PROJEXA sync complete', 'Data refreshed from PROJEXA.', ui.ButtonSet.OK);
      }
    } else {
      ui.alert('PROJEXA sync failed', body.error || ('HTTP ' + status), ui.ButtonSet.OK);
    }
  } catch (err) {
    ui.alert('PROJEXA sync failed', String(err), ui.ButtonSet.OK);
  }
}
`;
}
