"use client";

// R42 seq22 (M28 FORM archetype, S3 module 3/3): the Work Progress entry form.
//
// R67 D-28 (R-071/R-078). The controls are now written out here rather than
// generated by FormSection/FieldRenderer, for three reasons the audit named and
// the generic renderer cannot serve:
//
//  1. ORDER. The field order has to read top-to-bottom as the site engineer
//     thinks -- Activity, BOQ line item, Date, Quantity done, % complete,
//     Entry basis -- and FormSection reorders by fieldStatus, always putting
//     every OPTIONAL field last.
//  2. "BOQ line item" WAS BURIED. Being optional, FormSection filed it under
//     "More details", collapsed by default -- so the one field the Work
//     Progress Report depends on was the one field nobody saw. It is now in the
//     main flow, labelled with what it is for. "More details" keeps exactly
//     what it should: Remarks and Site photo.
//  3. THE UNIT ADORNMENT. "Quantity done" is meaningless without the unit it is
//     counted in; FieldRenderer has no adornment slot at all.
//
// Everything NOT about layout is unchanged and deliberately so: the offline
// queue, the photo upload path, and the BOQ selector R47-005 added all behave
// exactly as before.
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { ChevronDown, ChevronRight } from "lucide-react";
import { FormScreen, type FieldMessage } from "@fchecklist/veridian-ui-kit/screens";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { createClient } from "@/lib/supabase/client";
import { messageFor } from "@/lib/task-errors";
// R67 B-09 (DE-22): the required-field rule and the Save button's own words
// live beside the server's rule, not inside this component -- see that
// module's header for why.
import { missingFieldNames, missingProgressFields, submitLabelFor } from "@/lib/work-progress-form-fields";
import {
  enqueueWorkProgressEntry,
  listQueuedWorkProgressEntries,
  syncQueuedWorkProgressEntries,
  uploadQueuedPhoto,
  type QueuedWorkProgressEntry,
} from "@/lib/offline/work-progress-queue";

type Activity = { id: string; name: string; unit: string | null };
type BoqLineItem = { id: string; itemCode: string | null; description: string; unit: string; rate: string };
type Boq = { id: string; version: number; status: string; title: string };

export const BOQ_LINE_LABEL = "BOQ line item (optional - needed for the Work Progress Report)";
export const PERCENT_HINT = "% of this BOQ line; the report uses quantity x rate for amounts";
export const ENTRY_BASIS_HINT = "Entry basis applies to both the quantity and the percent above.";
export const QUANTITY_PLACEHOLDER_NO_ACTIVITY = "Pick an activity first";

const ENTRY_BASIS_OPTIONS = [
  { value: "DELTA", label: "Delta -- this entry adds to progress already logged" },
  { value: "SNAPSHOT", label: "Snapshot -- this entry replaces the running total" },
];

const REQUIRED_FIELDS = ["activityId", "entryDate", "quantityDone", "percentComplete", "entryBasis"] as const;

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}


export default function WorkProgressFormClient({ projectId, onLogged }: { projectId: string; onLogged: () => void }) {
  const router = useRouter();
  const [activities, setActivities] = useState<Activity[]>([]);
  const [lineItems, setLineItems] = useState<BoqLineItem[]>([]);
  // R47-005 (fault R46M13_TC30_01): every BOQ in the project, plus which one is
  // currently selected. Before this, the form resolved exactly ONE "current"
  // BOQ and offered no way to reach any other.
  const [boqs, setBoqs] = useState<Boq[]>([]);
  const [selectedBoqId, setSelectedBoqId] = useState<string | null>(null);
  const [values, setValues] = useState<Record<string, unknown>>({ entryDate: todayIso(), entryBasis: "DELTA" });
  const [messages, setMessages] = useState<FieldMessage[]>([]);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [scope, setScope] = useState<string | null>(null);
  const [queued, setQueued] = useState<QueuedWorkProgressEntry[]>([]);
  const [moreOpen, setMoreOpen] = useState(false);
  const [photo, setPhoto] = useState<File | null>(null);

  useEffect(() => {
    let cancelled = false;
    createClient().auth.getUser().then(({ data }) => { if (!cancelled) setScope(data.user?.id ?? null); });
    return () => { cancelled = true; };
  }, []);

  const refreshQueued = useCallback(async () => {
    if (!scope) return;
    setQueued(await listQueuedWorkProgressEntries(scope));
  }, [scope]);

  useEffect(() => { refreshQueued(); }, [refreshQueued]);

  useEffect(() => {
    fetch(`/api/work-progress/activities?projectId=${encodeURIComponent(projectId)}`)
      .then((r) => r.json())
      .then((data) => setActivities(data.activities ?? []))
      .catch(() => toast.error("Couldn't load activities"));

    // R47-005 (fault R46M13_TC30_01, reproduced live in production 2026-08-25):
    // this used to resolve ONE "current" BOQ -- approved, else submitted, else
    // highest version -- fetch only that BOQ's line items, and offer no BOQ
    // selector anywhere on the form. Every other BOQ in the project was
    // therefore unreachable for recording progress against. The resolution
    // order is KEPT as the DEFAULT selection (so the common single-BOQ case
    // behaves exactly as before), but the full list is now retained and offered
    // whenever the project holds more than one.
    fetch(`/api/scope?projectId=${encodeURIComponent(projectId)}`)
      .then((r) => r.json())
      .then((data) => {
        const all: Boq[] = data.boqs ?? [];
        if (all.length === 0) return;
        setBoqs(all);
        const current =
          all.find((b) => b.status === "approved") ??
          all.find((b) => b.status === "submitted") ??
          [...all].sort((a, b) => b.version - a.version)[0];
        setSelectedBoqId(current.id);
        setValues((v) => ({ ...v, boqId: current.id }));
      })
      .catch(() => { /* optional context -- a missing BOQ link is not a form-blocking error */ });
  }, [projectId]);

  // Loads the selected BOQ's line items. Org and project scoping are unchanged:
  // this only ever fetches a BOQ id that /api/scope?projectId= already returned
  // for this project, and that route is org-scoped server-side.
  useEffect(() => {
    if (!selectedBoqId) return;
    let cancelled = false;
    fetch(`/api/scope/${selectedBoqId}`)
      .then((r) => r.json())
      .then((boq) => { if (!cancelled) setLineItems(boq.lineItems ?? []); })
      .catch(() => { if (!cancelled) setLineItems([]); });
    return () => { cancelled = true; };
  }, [selectedBoqId]);

<<<<<<< HEAD
  // R67 B-09: whether THIS project is measured against a BOQ at all. The
  // /api/scope fetch below already answers it, so this needs no extra call.
  const projectHasBoq = boqs.length > 0;
  const missingRequired = missingProgressFields(values, projectHasBoq);

  const columns: ScreenColumn[] = [
    { label: "Activity", field: "activityId", control: "SELECT", type: "text", required: true, fieldStatus: "REQUIRED", options: activities.map((a) => ({ value: a.id, label: a.unit ? `${a.name} (${a.unit})` : a.name })) },
    // Shown only when the project actually holds more than one BOQ -- with a
    // single BOQ the choice is not a choice, and an extra control on a site
    // engineer's form is cost with no benefit (projexa#94's own rule).
    ...(boqs.length > 1
      ? [{
          label: "BOQ", field: "boqId", control: "SELECT", type: "text", required: false, fieldStatus: "OPTIONAL",
          options: [...boqs]
            .sort((a, b) => b.version - a.version || a.title.localeCompare(b.title))
            .map((b) => ({ value: b.id, label: `${b.title} (v${b.version}, ${b.status})` })),
        } as ScreenColumn]
      : []),
    // R67 B-09: REQUIRED whenever the project actually has a BOQ, matching
    // the one rule the API route now enforces for both callers
    // (construction-progress-service.createEntry). An entry with no line on a
    // project measured against a BOQ cannot be rolled up, cannot be valued,
    // and vanishes from the Work Progress Report -- so the form must ask for
    // it up front rather than let the server refuse after the click. On a
    // project with NO BOQ there is nothing to link to and the field stays
    // optional (and its picker empty), which is why this is derived from
    // `projectHasBoq` rather than hard-coded either way.
    { label: "BOQ line", field: "boqLineItemId", control: "SELECT", type: "text", required: projectHasBoq, fieldStatus: projectHasBoq ? "REQUIRED" : "OPTIONAL", options: lineItems.map((l) => ({ value: l.id, label: l.itemCode ? `${l.itemCode} -- ${l.description}` : l.description })) },
    { label: "Line item description", field: "description", control: "DERIVED", type: "text", fieldStatus: "OPTIONAL" },
    { label: "Unit", field: "unit", control: "DERIVED", type: "text", fieldStatus: "OPTIONAL" },
    { label: "Rate", field: "rate", control: "DERIVED", type: "number", fieldStatus: "OPTIONAL" },
    { label: "Date", field: "entryDate", control: "DATE", type: "date", required: true, fieldStatus: "REQUIRED" },
    { label: "Quantity done", field: "quantityDone", control: "NUMBER", type: "number", required: true, fieldStatus: "REQUIRED" },
    { label: "% complete", field: "percentComplete", control: "NUMBER", type: "number", required: true, fieldStatus: "REQUIRED" },
    { label: "Entry basis", field: "entryBasis", control: "RADIO", type: "text", required: true, fieldStatus: "REQUIRED", options: ENTRY_BASIS_OPTIONS },
    { label: "Remarks", field: "remarks", control: "TEXT", type: "text", fieldStatus: "OPTIONAL", required: false },
    { label: "Site photo", field: "photo", control: "FILE", type: "file", fieldStatus: "OPTIONAL", required: false },
  ];
=======
  const selectedActivity = activities.find((a) => a.id === values.activityId);
  const selectedLine = lineItems.find((l) => l.id === values.boqLineItemId);
  // The BOQ line's unit wins when a line is chosen, exactly as VERIDIAN's own
  // resolveProgressUnit() decides it for the list and the report -- one rule,
  // not a screen-local second opinion.
  const unit = selectedLine?.unit ?? selectedActivity?.unit ?? null;
>>>>>>> 57f8c07 (r67(D21): D-28 work progress — an object page, readable BOQ lines, a form that reads top to bottom)

  function setField(field: string, value: unknown) {
    if (field === "boqId") {
      // Switching BOQ invalidates the line selected from the previous one, so
      // clear it. Leaving a stale line id in place would post progress against
      // a line the user can no longer see.
      setSelectedBoqId(value as string);
      setValues((v) => ({ ...v, boqId: value, boqLineItemId: undefined }));
      return;
    }
    setValues((v) => ({ ...v, [field]: value }));
    setFieldErrors((e) => (e[field] ? { ...e, [field]: "" } : e));
  }

  const missingCount = REQUIRED_FIELDS.filter((f) => values[f] === undefined || values[f] === null || values[f] === "").length;

  async function handleSubmit() {
<<<<<<< HEAD
    const missing = missingRequired;
=======
    const missing = REQUIRED_FIELDS.filter((f) => values[f] === undefined || values[f] === null || values[f] === "");
>>>>>>> 57f8c07 (r67(D21): D-28 work progress — an object page, readable BOQ lines, a form that reads top to bottom)
    if (missing.length > 0) {
      // R67 B-09 (DE-22): NAME the fields, do not count them. "2 required
      // fields missing" makes the user hunt; "Activity, BOQ line" does not.
      setMessages([{ level: "error", text: `Still needed: ${missingFieldNames(missing)}` }]);
      return;
    }
    const pct = Number(values.percentComplete);
    if (Number.isNaN(pct) || pct < 0 || pct > 100) {
      setFieldErrors((e) => ({ ...e, percentComplete: "% complete must be between 0 and 100" }));
      setMessages([{ field: "percentComplete", level: "error", text: "% complete must be between 0 and 100" }]);
      return;
    }
    setMessages([]);
    setSubmitting(true);

    const payload = {
      projectId,
      activityId: values.activityId as string,
      boqLineItemId: (values.boqLineItemId as string) || undefined,
      entryDate: values.entryDate as string,
      quantityDone: Number(values.quantityDone),
      percentComplete: pct,
      entryBasis: values.entryBasis as "DELTA" | "SNAPSHOT",
      remarks: (values.remarks as string) || undefined,
    };
    const photoField = photo ? { blob: photo, name: photo.name, type: photo.type } : null;

    async function reset() {
      setValues({ entryDate: todayIso(), entryBasis: "DELTA" });
      setPhoto(null);
      onLogged();
    }

    if (typeof navigator !== "undefined" && !navigator.onLine) {
      if (!scope) { setMessages([{ level: "error", text: "Still verifying your session -- try again in a moment" }]); setSubmitting(false); return; }
      await enqueueWorkProgressEntry(scope, { ...payload, photo: photoField });
      toast.info("You're offline -- progress saved on this device, will sync automatically");
      await reset(); refreshQueued(); setSubmitting(false);
      return;
    }

    try {
      const res = await fetch("/api/work-progress", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        // R67 B-09 (D-03): the route answers a rule violation with a CODE.
        // Rendering it through the SAME dictionary the composer uses is what
        // makes both paths produce the same words -- "Pick a BOQ line", never
        // "itemCode" and never "boqLineItemId".
        if (typeof err.code === "string") {
          setMessages([{ field: "boqLineItemId", level: "error", text: messageFor(err.code) }]);
          setSubmitting(false);
          return;
        }
        throw new Error(err.error ?? "Failed to log progress");
      }
      const created = await res.json();
      // R42 seq22 fix: the online path never uploaded a photo before this.
      if (photo) {
        await uploadQueuedPhoto(created.id, { blob: photo, name: photo.name, type: photo.type }).catch(() => {
          toast.error("Progress logged, but the photo failed to upload");
        });
      }
      // R67 D-28: Save used to leave the user on an emptied form, with no way
      // to see the thing they had just made. They now land on it.
      setValues({ entryDate: todayIso(), entryBasis: "DELTA" });
      setPhoto(null);
      onLogged();
      router.push(`/work-progress/${created.id}?logged=1`);
    } catch (err) {
      if (err instanceof TypeError) {
        if (!scope) { setMessages([{ level: "error", text: "Still verifying your session -- try again in a moment" }]); }
        else {
          await enqueueWorkProgressEntry(scope, { ...payload, photo: photoField });
          toast.info("Network unavailable -- progress saved on this device, will sync automatically");
          await reset(); refreshQueued();
        }
      } else {
        setMessages([{ level: "error", text: err instanceof Error ? err.message : "Couldn't log progress" }]);
      }
    } finally {
      setSubmitting(false);
    }
  }

  useEffect(() => {
    if (!scope) return;
    const run = () => { if (typeof navigator !== "undefined" && navigator.onLine) syncQueuedWorkProgressEntries(scope).then(({ synced }) => { if (synced > 0) { toast.success(`Synced ${synced} queued ${synced === 1 ? "entry" : "entries"}`); onLogged(); } refreshQueued(); }); };
    run();
    window.addEventListener("online", run);
    return () => window.removeEventListener("online", run);
  }, [scope]);

<<<<<<< HEAD
  // R42 seq23 live-user finding: same fail-after-click gap caught on
  // Permits' Save applies here too -- Log Entry was clickable with required
  // fields still empty. See PermitObjectClient.tsx's own comment for the
  // GLOBAL rule this violated.
  //
  // R67 B-09: `boqLineItemId` joins the list whenever the project has a BOQ,
  // which is exactly the rule the API route enforces -- so the button is
  // disabled for the same reason the server would have refused, instead of
  // the user finding out after the click.
  const missingCount = missingRequired.length;

=======
>>>>>>> 57f8c07 (r67(D21): D-28 work progress — an object page, readable BOQ lines, a form that reads top to bottom)
  return (
    <FormScreen
      breadcrumb="Work Progress / Log entry"
      title="Log Work Progress"
      onSubmit={handleSubmit}
      submitLabel={submitLabelFor(missingRequired)}
      submitting={submitting}
      submitDisabled={missingCount > 0}
      submitDisabledReason={missingCount > 0 ? missingFieldNames(missingRequired) : undefined}
      messages={messages}
      banner={queued.length > 0 ? (
        <div className="mx-4 mt-3 rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-[12.5px] text-amber-900">
          {queued.length} {queued.length === 1 ? "entry" : "entries"} queued on this device, will sync automatically.
        </div>
      ) : undefined}
    >
      <section className="border-t border-ct-border px-4 py-3">
        <h3 className="mb-3 text-[13px] font-medium text-ct-navy">Progress entry</h3>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <FormField label="Activity" required error={fieldErrors.activityId}>
            {(props) => (
              <Select value={(values.activityId as string) ?? ""} onValueChange={(v) => setField("activityId", v)}>
                <SelectTrigger {...props}><SelectValue placeholder="Choose an activity" /></SelectTrigger>
                <SelectContent>
                  {activities.map((a) => (
                    <SelectItem key={a.id} value={a.id}>{a.unit ? `${a.name} (${a.unit})` : a.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </FormField>

          {/* Shown only when the project actually holds more than one BOQ --
              with a single BOQ the choice is not a choice (projexa#94's rule). */}
          {boqs.length > 1 && (
            <FormField label="BOQ">
              {(props) => (
                <Select value={(values.boqId as string) ?? ""} onValueChange={(v) => setField("boqId", v)}>
                  <SelectTrigger {...props}><SelectValue placeholder="Choose a BOQ" /></SelectTrigger>
                  <SelectContent>
                    {[...boqs]
                      .sort((a, b) => b.version - a.version || a.title.localeCompare(b.title))
                      .map((b) => <SelectItem key={b.id} value={b.id}>{`${b.title} (v${b.version}, ${b.status})`}</SelectItem>)}
                  </SelectContent>
                </Select>
              )}
            </FormField>
          )}

          <FormField
            label={BOQ_LINE_LABEL}
            className="sm:col-span-2"
            hint={selectedLine ? `${selectedLine.description} · ${selectedLine.unit} · rate ${selectedLine.rate}` : undefined}
          >
            {(props) => (
              <Select value={(values.boqLineItemId as string) ?? ""} onValueChange={(v) => setField("boqLineItemId", v)}>
                <SelectTrigger {...props}><SelectValue placeholder="Choose a BOQ line" /></SelectTrigger>
                <SelectContent>
                  {lineItems.map((l) => (
                    <SelectItem key={l.id} value={l.id}>{l.itemCode ? `${l.itemCode} - ${l.description}` : l.description}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </FormField>

          <FormField label="Date" required error={fieldErrors.entryDate}>
            {(props) => (
              <Input {...props} type="date" value={(values.entryDate as string) ?? ""} onChange={(e) => setField("entryDate", e.target.value)} />
            )}
          </FormField>

          {/* The unit sits INSIDE the control, because a quantity typed with no
              unit in sight is the mis-keying this module keeps producing. */}
          <FormField label="Quantity done" required error={fieldErrors.quantityDone}>
            {(props) => (
              <div className="relative">
                <Input
                  {...props}
                  type="number"
                  inputMode="decimal"
                  min={0}
                  className={unit ? "pr-14" : undefined}
                  placeholder={selectedActivity ? undefined : QUANTITY_PLACEHOLDER_NO_ACTIVITY}
                  value={(values.quantityDone as string) ?? ""}
                  onChange={(e) => setField("quantityDone", e.target.value)}
                />
                {unit && (
                  <span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-[12px] text-px-muted">{unit}</span>
                )}
              </div>
            )}
          </FormField>

          <FormField label="% complete" required hint={PERCENT_HINT} error={fieldErrors.percentComplete}>
            {(props) => (
              <Input
                {...props}
                type="number"
                inputMode="decimal"
                min={0}
                max={100}
                value={(values.percentComplete as string) ?? ""}
                onChange={(e) => setField("percentComplete", e.target.value)}
              />
            )}
          </FormField>

          <FormField label="Entry basis" required hint={ENTRY_BASIS_HINT} className="sm:col-span-2">
            {(props) => (
              <RadioGroup
                aria-describedby={props["aria-describedby"]}
                aria-required={props["aria-required"]}
                value={(values.entryBasis as string) ?? "DELTA"}
                onValueChange={(v) => setField("entryBasis", v)}
                className="gap-1.5"
              >
                {ENTRY_BASIS_OPTIONS.map((option) => (
                  <div key={option.value} className="flex items-center gap-2">
                    <RadioGroupItem value={option.value} id={`${props.id}-${option.value}`} />
                    <Label htmlFor={`${props.id}-${option.value}`} className="text-[12.5px] font-normal">{option.label}</Label>
                  </div>
                ))}
              </RadioGroup>
            )}
          </FormField>
        </div>

        {/* "More details" now holds exactly what it should: the two fields a
            site engineer genuinely may skip. */}
        <div className="mt-3">
          <button
            type="button"
            onClick={() => setMoreOpen((v) => !v)}
            className="inline-flex items-center gap-1 text-[12.5px] text-ct-muted hover:text-ct-navy"
          >
            {moreOpen ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
            More details
          </button>
          {moreOpen && (
            <div className="mt-2 grid grid-cols-1 gap-3 sm:grid-cols-2">
              <FormField label="Remarks" className="sm:col-span-2">
                {(props) => (
                  <Textarea {...props} rows={3} value={(values.remarks as string) ?? ""} onChange={(e) => setField("remarks", e.target.value)} />
                )}
              </FormField>
              <FormField label="Site photo" className="sm:col-span-2" hint={photo ? `Selected: ${photo.name}` : undefined}>
                {(props) => (
                  <Input {...props} type="file" accept="image/*" onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} />
                )}
              </FormField>
            </div>
          )}
        </div>
      </section>
    </FormScreen>
  );
}
