import { NextResponse } from "next/server";
import { requireAuth, requireRole, ROLE_GROUPS, ALL_ORG_ROLES } from "@/lib/supabase/auth-guard";
import { createClient } from "@/lib/supabase/server";
import { withTiming } from "@/lib/with-timing";

// R48_NO_INVITE_UI_01: org-admin user provisioning. Ruled at L5 -- SAP,
// Dynamics 365 and Odoo all place user provisioning under organisation admin
// settings.
//
// THE LINK IS GENERATED BY THIS APP, NOT BY SUPABASE. Supabase's own email
// templates render {{ .SiteURL }}, and Site URL on the projexa auth project
// is still http://localhost:3000 -- so anything Supabase mails out is dead on
// arrival. The token below is ours, the URL below is ours, and redemption
// goes through our own /invite/<token> route. Nothing here depends on the
// redirect allowlist or on Supabase sending mail at all.
//
// Enforcement is SERVER-SIDE here (requireRole) *and* in RLS
// (drizzle/0015_org_invites.sql). UAT criterion C17 is explicit that a
// client-only guard is a FAIL -- the Settings UI's admin check is a UX
// affordance only; these two layers are the actual boundary.

export const GET = withTiming("GET", async function GET() {
  const ctx = await requireAuth();
  if (ctx.response) return ctx.response;
  const forbidden = requireRole(ctx, ROLE_GROUPS.ORG_ADMIN);
  if (forbidden) return forbidden;

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("org_invites")
    .select("id, email, role, token, created_at, expires_at, accepted_at, revoked_at")
    .eq("organization_id", ctx.organizationId!)
    .order("created_at", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ invites: data ?? [] });
});

export const POST = withTiming("POST", async function POST(req: Request) {
  const ctx = await requireAuth();
  if (ctx.response) return ctx.response;
  const forbidden = requireRole(ctx, ROLE_GROUPS.ORG_ADMIN);
  if (forbidden) return forbidden;

  const body = (await req.json().catch(() => null)) as { email?: string; role?: string } | null;
  const email = body?.email?.trim().toLowerCase();
  const role = body?.role?.trim() ?? "member";

  // UAT criterion C04 (INPUT_REJECTED) requires the message to name the field
  // and the reason, not a generic "invalid request".
  if (!email) {
    return NextResponse.json({ error: "Email is required to send an invitation." }, { status: 400 });
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: `Email "${email}" is not a valid email address.` }, { status: 400 });
  }
  if (!ALL_ORG_ROLES.includes(role as (typeof ALL_ORG_ROLES)[number])) {
    return NextResponse.json(
      { error: `Role "${role}" is not a valid role. Choose one of: ${ALL_ORG_ROLES.join(", ")}.` },
      { status: 400 }
    );
  }

  const supabase = await createClient();

  // Inviting somebody who is already in this organisation would otherwise
  // look like it worked and then never appear anywhere.
  const { data: existing } = await supabase
    .from("memberships")
    .select("user_id, profiles(email)")
    .eq("organization_id", ctx.organizationId!);
  const alreadyMember = (existing ?? []).some(
    (m) => (m.profiles as { email?: string } | null)?.email?.toLowerCase() === email
  );
  if (alreadyMember) {
    return NextResponse.json({ error: `${email} is already a member of this organisation.` }, { status: 409 });
  }

  const token = `${crypto.randomUUID()}${crypto.randomUUID()}`.replace(/-/g, "");
  const { data, error } = await supabase
    .from("org_invites")
    .insert({
      organization_id: ctx.organizationId!,
      email,
      role,
      token,
      invited_by: ctx.user!.id,
      expires_at: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    })
    .select("id, email, role, token, created_at, expires_at")
    .single();

  if (error) {
    // The partial unique index allows only one live invite per address.
    if (error.code === "23505") {
      return NextResponse.json(
        { error: `There is already a pending invitation for ${email}. Revoke it first to issue a new link.` },
        { status: 409 }
      );
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ invite: data }, { status: 201 });
});
