// GENERATED by FChecklist/projexa scripts/projexa-api-edge.mjs -- DO NOT EDIT BY HAND. Edit the sources in the projexa repo and regenerate:
//   src/lib/authz/api-write-policy.ts, src/lib/authz/roles.ts, ai-os/audit37/projexa-api-routes.json, ai-os/audit37/vercel-route-inventory.json
// The SAME bytes live in projexa ai-os/audit37/projexa-api/policy.generated.ts and compliance-tracker supabase/functions/projexa-api/.
// SOURCE_SHA256 is the hash of the data below; both repos' tests recompute it, so a hand edit of either copy fails CI.
export const SOURCE_SHA256 = "122618857bbfa6594366495f9ee0182f343ec7568ff191eaaeb893532600563a"

export const ROLE_GROUPS: Readonly<Record<string, readonly string[]>> = {"ORG_ADMIN":["owner","admin"],"PM_OR_ABOVE":["owner","admin","pm"],"FIELD":["owner","admin","pm","site_engineer"],"ANY_MEMBER":["owner","admin","pm","site_engineer","member"],"ANY_ROLE":["owner","admin","pm","site_engineer","member","client_viewer"]}

/** [pattern, tier] in the ORDER of src/lib/authz/api-write-policy.ts (the first match wins, so order is part of the policy). */
export const API_WRITE_POLICY: ReadonlyArray<readonly [string, string]> = [
  ["/access-review", "ORG_ADMIN"],
  ["/access-review/certifications/[id]", "ORG_ADMIN"],
  ["/ai/apply", "ANY_MEMBER"],
  ["/assistant", "ANY_MEMBER"],
  ["/attendance", "FIELD"],
  ["/attendance/bulk", "FIELD"],
  ["/attendance/summary/share", "PM_OR_ABOVE"],
  ["/audit-engagements", "ORG_ADMIN"],
  ["/audit-findings", "ORG_ADMIN"],
  ["/audit-findings/[id]", "ORG_ADMIN"],
  ["/billing-claims", "PM_OR_ABOVE"],
  ["/billing-claims/[id]", "PM_OR_ABOVE"],
  ["/board", "FIELD"],
  ["/change-orders", "PM_OR_ABOVE"],
  ["/change-orders/[id]", "PM_OR_ABOVE"],
  ["/classify", "ANY_MEMBER"],
  ["/companies", "ORG_ADMIN"],
  ["/compliance-register", "ORG_ADMIN"],
  ["/construction-budget/lines", "PM_OR_ABOVE"],
  ["/contact", "PUBLIC"],
  ["/conversations", "ANY_ROLE"],
  ["/conversations/[id]/messages", "ANY_ROLE"],
  ["/credit-notes", "PM_OR_ABOVE"],
  ["/credit-notes/[id]/submit", "PM_OR_ABOVE"],
  ["/customers", "PM_OR_ABOVE"],
  ["/customers/[id]", "PM_OR_ABOVE"],
  ["/design-materials", "PM_OR_ABOVE"],
  ["/discuss", "ANY_MEMBER"],
  ["/documents", "FIELD"],
  ["/documents/[id]", "FIELD"],
  ["/documents/[id]/dispose", "FIELD"],
  ["/documents/[id]/versions", "FIELD"],
  ["/drawings", "FIELD"],
  ["/drawings/[id]", "FIELD"],
  ["/email/send-digest", "ANY_MEMBER"],
  ["/email/inbound", "PUBLIC"],
  ["/email/[token]", "PUBLIC"],
  ["/employees", "ORG_ADMIN"],
  ["/employees/[id]", "ORG_ADMIN"],
  ["/expenses", "PM_OR_ABOVE"],
  ["/ffe", "PM_OR_ABOVE"],
  ["/ffe/[id]", "PM_OR_ABOVE"],
  ["/floor-plans", "PM_OR_ABOVE"],
  ["/floor-plans/[id]", "PM_OR_ABOVE"],
  ["/floor-plans/[id]/placements", "PM_OR_ABOVE"],
  ["/floor-plans/[id]/placements/[placementId]", "PM_OR_ABOVE"],
  ["/floor-plans/[id]/rooms", "PM_OR_ABOVE"],
  ["/floor-plans/[id]/rooms/[roomId]", "PM_OR_ABOVE"],
  ["/fraud-cases", "ORG_ADMIN"],
  ["/fraud-cases/[id]", "ORG_ADMIN"],
  ["/hr/departments", "ORG_ADMIN"],
  ["/integrations/google-sheets/setup", "ORG_ADMIN"],
  ["/integrations/google-sheets/disconnect", "ORG_ADMIN"],
  ["/integrations/google-sheets/refresh", "ANY_MEMBER"],
  ["/integrations/google-sheets/webhook", "PUBLIC"],
  ["/inventory/items", "PM_OR_ABOVE"],
  ["/inventory/stock-entries", "FIELD"],
  ["/inventory/warehouses", "PM_OR_ABOVE"],
  ["/journal-entries", "ORG_ADMIN"],
  ["/journal-entries/[id]/submit", "ORG_ADMIN"],
  ["/knowledge-base", "FIELD"],
  ["/knowledge-base/[id]", "FIELD"],
  ["/kpi-entries", "FIELD"],
  ["/kpi-entries/[id]/approve", "FIELD"],
  ["/kpis", "PM_OR_ABOVE"],
  ["/labour-roster", "FIELD"],
  ["/labour-roster/[id]", "FIELD"],
  ["/labour-roster/import", "FIELD"],
  ["/leads", "PM_OR_ABOVE"],
  ["/leads/[id]", "PM_OR_ABOVE"],
  ["/leads/bulk-reassign", "PM_OR_ABOVE"],
  ["/leave/balances", "ORG_ADMIN"],
  ["/leave/requests", "ANY_MEMBER"],
  ["/leave/requests/[id]/decision", "PM_OR_ABOVE"],
  ["/materials", "FIELD"],
  ["/materials/[id]", "FIELD"],
  ["/materials/issues", "FIELD"],
  ["/materials/master", "FIELD"],
  ["/materials/master/[id]", "FIELD"],
  ["/meetings", "FIELD"],
  ["/meetings/[id]", "FIELD"],
  ["/meetings/[id]/outcomes", "FIELD"],
  ["/milestones", "PM_OR_ABOVE"],
  ["/milestones/[id]", "PM_OR_ABOVE"],
  ["/moms", "FIELD"],
  ["/moms/[id]", "FIELD"],
  ["/moms/[id]/action-items", "FIELD"],
  ["/moms/[id]/generate-intelligence", "FIELD"],
  ["/moms/[id]/share-links", "PM_OR_ABOVE"],
  ["/moms/share-links/[linkId]", "PM_OR_ABOVE"],
  ["/local-first/prepare-report", "ANY_ROLE"],
  ["/local-first/client-error", "ANY_ROLE"],
  ["/mood-boards", "PM_OR_ABOVE"],
  ["/mood-boards/[id]", "PM_OR_ABOVE"],
  ["/mood-boards/[id]/items/[itemId]", "PM_OR_ABOVE"],
  ["/notifications/[id]/read", "ANY_ROLE"],
  ["/opportunities", "PM_OR_ABOVE"],
  ["/opportunities/[id]", "PM_OR_ABOVE"],
  ["/opportunities/bulk-reassign", "PM_OR_ABOVE"],
  ["/org/invites/accept", "ANY_ROLE"],
  ["/org/invites", "ORG_ADMIN"],
  ["/org/invites/[id]", "ORG_ADMIN"],
  ["/org-members/[id]", "ORG_ADMIN"],
  ["/org/provision", "PUBLIC"],
  ["/org/repair", "ORG_ADMIN"],
  ["/organization/currency", "ORG_ADMIN"],
  ["/organization/email-schedule", "ORG_ADMIN"],
  ["/payroll/employees/[id]/income-tax-slab", "ORG_ADMIN"],
  ["/payroll/employees/[id]/tax-exemptions", "ORG_ADMIN"],
  ["/payroll/income-tax-slabs", "ORG_ADMIN"],
  ["/payroll/payslips/[id]/finalize", "ORG_ADMIN"],
  ["/payroll/payslips/[id]/tds", "ORG_ADMIN"],
  ["/payroll/runs", "ORG_ADMIN"],
  ["/payroll/runs/[id]/process", "ORG_ADMIN"],
  ["/payroll/salary-components", "ORG_ADMIN"],
  ["/payroll/salary-structures", "ORG_ADMIN"],
  ["/payroll/statutory-rules", "ORG_ADMIN"],
  ["/permits", "PM_OR_ABOVE"],
  ["/permits/[id]", "PM_OR_ABOVE"],
  ["/pill-usage", "ANY_ROLE"],
  ["/policies", "ORG_ADMIN"],
  ["/policies/[id]", "ORG_ADMIN"],
  ["/procurement/goods-receipts", "PM_OR_ABOVE"],
  ["/procurement/goods-receipts/[id]/submit", "PM_OR_ABOVE"],
  ["/procurement/purchase-orders", "PM_OR_ABOVE"],
  ["/procurement/purchase-orders/[id]", "PM_OR_ABOVE"],
  ["/procurement/purchase-orders/[id]/submit", "PM_OR_ABOVE"],
  ["/procurement/quotations", "PM_OR_ABOVE"],
  ["/procurement/requisitions", "PM_OR_ABOVE"],
  ["/procurement/requisitions/[id]/submit", "PM_OR_ABOVE"],
  ["/procurement/rfqs", "PM_OR_ABOVE"],
  ["/procurement/rfqs/[id]/send", "PM_OR_ABOVE"],
  ["/project-budgets", "PM_OR_ABOVE"],
  ["/project-budgets/[id]", "PM_OR_ABOVE"],
  ["/project-budgets/[id]/cancel", "PM_OR_ABOVE"],
  ["/project-budgets/[id]/submit", "PM_OR_ABOVE"],
  ["/projects", "PM_OR_ABOVE"],
  ["/projects/from-document", "ANY_MEMBER"],
  ["/projects/[id]", "PM_OR_ABOVE"],
  ["/projects/[id]/approvals", "PM_OR_ABOVE"],
  ["/punch-list", "FIELD"],
  ["/punch-list/[id]", "FIELD"],
  ["/purchase-orders", "PM_OR_ABOVE"],
  ["/quotations", "PM_OR_ABOVE"],
  ["/quotations/[id]", "PM_OR_ABOVE"],
  ["/quotations/[id]/convert", "PM_OR_ABOVE"],
  ["/quotations/[id]/revisions", "PM_OR_ABOVE"],
  ["/recruitment/applications", "PM_OR_ABOVE"],
  ["/recruitment/applications/[id]/hire", "ORG_ADMIN"],
  ["/recruitment/applications/[id]/interviews", "PM_OR_ABOVE"],
  ["/recruitment/applications/[id]/stage", "PM_OR_ABOVE"],
  ["/recruitment/candidates", "PM_OR_ABOVE"],
  ["/recruitment/interviews/[id]/feedback", "PM_OR_ABOVE"],
  ["/recruitment/job-openings", "ORG_ADMIN"],
  ["/recruitment/job-openings/[id]/status", "ORG_ADMIN"],
  ["/reports/definitions/[id]/run", "FIELD"],
  ["/reports/[reportName]/share", "PM_OR_ABOVE"],
  ["/rfis", "FIELD"],
  ["/rfis/[id]", "FIELD"],
  ["/risks", "PM_OR_ABOVE"],
  ["/risks/[id]", "PM_OR_ABOVE"],
  ["/sales-invoices", "PM_OR_ABOVE"],
  ["/sales-invoices/[id]/cancel", "PM_OR_ABOVE"],
  ["/sales-invoices/[id]/payments", "PM_OR_ABOVE"],
  ["/sales-invoices/[id]/submit", "PM_OR_ABOVE"],
  ["/sales-orders", "PM_OR_ABOVE"],
  ["/sales-orders/[id]", "PM_OR_ABOVE"],
  ["/sales-orders/bulk-status", "PM_OR_ABOVE"],
  ["/schedule/baselines", "PM_OR_ABOVE"],
  ["/schedule/import", "PM_OR_ABOVE"],
  ["/schedule/sprints", "PM_OR_ABOVE"],
  ["/schedule/sprints/[id]", "PM_OR_ABOVE"],
  ["/schedule/sprints/[id]/issues", "PM_OR_ABOVE"],
  ["/schedule/tasks", "FIELD"],
  ["/schedule/tasks/[id]", "FIELD"],
  ["/schedule/tasks/[id]/completion", "PM_OR_ABOVE"],
  ["/schedule/workload", "PM_OR_ABOVE"],
  ["/scope", "PM_OR_ABOVE"],
  ["/scope/[id]/approve", "PM_OR_ABOVE"],
  ["/scope/[id]/revisions", "PM_OR_ABOVE"],
  ["/scope/[id]/submit", "PM_OR_ABOVE"],
  ["/scope/categories", "PM_OR_ABOVE"],
  ["/scope/categories/[id]", "PM_OR_ABOVE"],
  ["/scope/cost-visibility", "ORG_ADMIN"],
  ["/scope/[id]", "PM_OR_ABOVE"],
  ["/scope/import", "PM_OR_ABOVE"],
  ["/scope/line-items/[id]", "PM_OR_ABOVE"],
  ["/screen-drafts", "FIELD"],
  ["/screen-drafts/[id]", "FIELD"],
  ["/site-diary", "FIELD"],
  ["/site-instructions", "PM_OR_ABOVE"],
  ["/submittals", "FIELD"],
  ["/submittals/[id]", "FIELD"],
  ["/timesheets", "ANY_MEMBER"],
  ["/timesheets/[id]/approve", "PM_OR_ABOVE"],
  ["/timesheets/[id]/reject", "PM_OR_ABOVE"],
  ["/timesheets/[id]/submit", "ANY_MEMBER"],
  ["/timesheets/submit-day", "ANY_MEMBER"],
  ["/timesheets/review-day", "PM_OR_ABOVE"],
  ["/timesheets/[id]", "ANY_MEMBER"],
  ["/tasks", "ANY_MEMBER"],
  ["/todos", "ANY_MEMBER"],
  ["/todos/[id]", "ANY_MEMBER"],
  ["/user-preference/last-project", "ANY_ROLE"],
  ["/vendor-risk", "ORG_ADMIN"],
  ["/vendors", "PM_OR_ABOVE"],
  ["/vendors/[id]", "PM_OR_ABOVE"],
  ["/vendors/[id]/bank-accounts", "PM_OR_ABOVE"],
  ["/vendors/[id]/portal-links", "PM_OR_ABOVE"],
  ["/vendors/[id]/portal-links/[linkId]", "PM_OR_ABOVE"],
  ["/vendors/[id]/qualification", "PM_OR_ABOVE"],
  ["/vendors/[id]/sanction-checks", "PM_OR_ABOVE"],
  ["/wiki", "FIELD"],
  ["/wiki/[id]", "FIELD"],
  ["/work-progress", "FIELD"],
  ["/work-progress/[id]", "FIELD"],
  ["/work-progress/activities", "FIELD"],
  ["/work-progress/photos", "FIELD"],
  ["/work-progress/report/share", "PM_OR_ABOVE"],
]
export const DEFAULT_WRITE_TIER = "FIELD"
export const MUTATING_METHODS: ReadonlySet<string> = new Set(["DELETE","PATCH","POST","PUT"])

export type EdgeMethodSpec = {
  upstream: string; acting_user?: "explicit" | "session"; fallback: string; required_query?: Record<string, string>; timeout_ms?: number;
  search_params?: string[]; body?: "json"; body_actor_email?: "always"; error_style?: "veridian" | "plain"
}
/** DENY BY DEFAULT: the only routes the function answers. Generated from ai-os/audit37/projexa-api-routes.json. */
export const EDGE_ROUTES: ReadonlyArray<{ route: string; methods: Readonly<Record<string, EdgeMethodSpec>> }> = [
  {"route":"/api/dashboard/project/:projectId","methods":{"GET":{"upstream":"/dashboard/{projectId}","acting_user":"explicit","fallback":"Failed to load project dashboard"}}},
  {"route":"/api/exceptions","methods":{"GET":{"upstream":"/exceptions?projectId={query:projectId}","required_query":{"projectId":"projectId query param is required"},"timeout_ms":60000,"fallback":"Failed to load the exceptions report"}}},
  {"route":"/api/reports/boq-analysis","methods":{"GET":{"upstream":"/reports/boq-analysis","search_params":["projectId","sortBy","direction"],"fallback":"Failed to load the profit & loss analysis"}}},
  {"route":"/api/scope/line-items/:id","methods":{"PATCH":{"upstream":"/scope/line-items/{id}","acting_user":"explicit","body":"json","fallback":"Failed to update line item budget"}}},
  {"route":"/api/documents/:id","methods":{"GET":{"upstream":"/documents/{id}","fallback":"Failed to load document"},"PATCH":{"upstream":"/documents/{id}","body":"json","fallback":"Failed to update document"}}},
  {"route":"/api/drawings/:id/document-url","methods":{"GET":{"upstream":"/drawings/{id}/document-url","error_style":"plain","fallback":"Couldn't open this drawing's file"}}},
  {"route":"/api/permits/:id","methods":{"GET":{"upstream":"/permits/{id}","fallback":"Failed to load permit"},"PATCH":{"upstream":"/permits/{id}","body":"json","body_actor_email":"always","fallback":"Failed to update permit"},"DELETE":{"upstream":"/permits/{id}","fallback":"Failed to delete permit"}}},
]

/** The data SOURCE_SHA256 is computed over (both repos' tests recompute the hash from this). */
export function sourceData() {
  return { roleGroups: ROLE_GROUPS, policy: API_WRITE_POLICY, defaultTier: DEFAULT_WRITE_TIER, mutatingMethods: [...MUTATING_METHODS], edgeRoutes: EDGE_ROUTES }
}

function matchesPattern(pattern: string, segments: readonly string[]): boolean {
  const patternSegments = pattern.split("/").filter(Boolean)
  if (patternSegments.length !== segments.length) return false
  return patternSegments.every((p, i) => (p.startsWith("[") && p.endsWith("]")) || p === segments[i])
}

export function resolveWriteTier(pathname: string): string {
  const segments = pathname.replace(/^\/api/, "").split("/").filter(Boolean)
  if (segments.length === 0) return DEFAULT_WRITE_TIER
  for (const [pattern, tier] of API_WRITE_POLICY) if (matchesPattern(pattern, segments)) return tier
  let best: { depth: number; tier: string } | null = null
  for (const [pattern, tier] of API_WRITE_POLICY) {
    const depth = pattern.split("/").filter(Boolean).length
    if (depth >= segments.length) continue
    if (!matchesPattern(pattern, segments.slice(0, depth))) continue
    if (!best || depth > best.depth) best = { depth, tier }
  }
  return best?.tier ?? DEFAULT_WRITE_TIER
}

/** null role = authenticated with no membership: the handler's 400 decides, not a 403 (same as the original). */
export function checkApiWriteAccess(method: string, pathname: string, role: string | null): { allowed: true } | { allowed: false; tier: string } {
  if (!MUTATING_METHODS.has(method.toUpperCase())) return { allowed: true }
  const tier = resolveWriteTier(pathname)
  if (tier === "PUBLIC") return { allowed: true }
  if (role == null) return { allowed: true }
  const allowedRoles = ROLE_GROUPS[tier] ?? []
  if (allowedRoles.includes(role)) return { allowed: true }
  return { allowed: false, tier }
}
